Added todo list
oxbee/JS-canvas-lessons pull request #4
Opened 2018-03-21 15:59 UTC by nastya1111

2018-03-21 16:03 UTC, oxbee requested changes
Fix comments please :)

2018-03-21 16:03 UTC, oxbee commented on Lesson#2dev.html
> +//TODO: зробити тестові завдання і отримати суші)
Wrong HTML comments 
Please use \<!-- bla bla bla -->

2018-03-22 07:52 UTC, nastya1111 commented
This was fixed.

2018-03-22 08:51 UTC, oxbee approved these changes

2018-03-22 08:54 UTC, merged